# Generated by Django 4.2.6 on 2023-10-09 20:49

import Media.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('size', models.PositiveBigIntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_upload', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(null=True, upload_to=Media.models.uploaded)),
                ('quality', models.CharField(max_length=100)),
                ('length', models.PositiveBigIntegerField()),
                ('content', models.FileField(blank=True, null=True, upload_to=Media.models.uploaded)),
                ('preview', models.FileField(blank=True, null=True, upload_to=Media.models.uploaded)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('size', models.PositiveBigIntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_upload', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(null=True, upload_to=Media.models.uploaded)),
                ('quality', models.CharField(max_length=100)),
                ('content', models.ImageField(blank=True, null=True, upload_to=Media.models.uploaded)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
